[package]
name = "redis"
version = "0.12.1-alpha.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>", "Jan-Erik Rediger <janerik@fnordig.de>", "Atsushi Koge <atuk721@gmail.com>", "hedgar2017 <hedgar2017@gmail.com>"]
keywords = ["redis", "database"]
description = "Redis driver for Rust."
homepage = "https://github.com/mitsuhiko/redis-rs"
repository = "https://github.com/mitsuhiko/redis-rs"
documentation = "https://docs.rs/redis"
# XXX: some code here is MIT licensed (cluster). Resolve before releasing
license = "BSD-3-Clause"
readme = "README.md"
edition = "2018"

[dependencies]
dtoa = "0.4"
itoa = "0.4.3"
percent-encoding = "2.1"
sha1 = ">= 0.2, < 0.7"
url = "2.1"
combine = "3.8.1"
bytes = "0.4"
futures = "0.1"
tokio-executor = { version = "0.1", optional = true }
tokio-tcp = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
tokio-sync = "0.1"
crc16 = { version = "0.4.0", optional = true }
rand = { version = "0.7.0", optional = true }

[features]
default = ["executor", "geospatial"]

geospatial = []
executor = ["tokio-executor"]
cluster = ["crc16", "rand"]

[target.'cfg(unix)'.dependencies]
tokio-uds = { version = "0.2" }

[dev-dependencies]
rand = "0.7.0"
net2 = "0.2"
assert_approx_eq = "1.0"
fnv = "1.0.5"
criterion = "0.2"
partial-io = { version = "0.3", features = ["tokio", "quickcheck"] }
quickcheck = "0.6"
tokio = "0.1"

[[bench]]
name = "bench_basic"
harness = false
